//USER CONTEXT
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const TOKEN_EXPIRED = "TOKEN_EXPIRED";

//GAME USER CONTEXT
export const GET_GAME_USER_LIST_SUCCESS = "GET_GAME_USER_LIST_SUCCESS";
export const GET_GAME_USER_LIST_FAILED = "GET_GAME_USER_LIST_FAILED";
